    image: node:latest
    
    before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl

    stages:
      - builds
      - test
      - production

    cache:
      paths:
        - node_modules/

    install_dependencies:
      stage: builds
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

    testing_testing:
      stage: test
      script: npm test
      
    deploying:
      type: deploy
      stage: production
      image: ruby:latest
      script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
      only:
        - production      